global_vars:
  - name: assets
    type: echo
    params:
      echo: "~/.config/espanso/match/assets"
  - name: inj-cat
    type: echo
    params:
      echo: ""
  - name: catasset
    type: shell
    depends_on: ["inj-cat"]
    params:
      cmd: "cat ~/.config/espanso/match/assets/{{inj-cat}}.txt"
